source "https://rubygems.org"

ruby ">= 3.2"

gem "roda", "~> 3.0"
gem "tilt", "~> 2.0"
gem "erubi", "~> 1.0"
gem "sqlite3", "~> 2.0"

group :production do
  gem "lamby", "~> 6.0"
end

group :development do
  gem "puma", "~> 6.0"
  gem "rackup", "~> 2.0"
  gem "rake", "~> 13.0"
end

group :test do
  gem "rspec", "~> 3.0"
  gem "rack-test", "~> 2.0"
end
